### ISSUE TITLE
[Indigo] [DatePicker] Add GMT Support to Magic Modifier.

### ISSUE THREAD

**Issue by lilingxi01** [david-fisher/320-S22-Track2#128]
# Description

In default, all input will be based on the local time. However, an engineer may need to input a GMT time in case that they find an error in the database (where stores GMT only). Therefore, they do not need to do any date conversions from GMT to local.

Solution will be easy: when their input is in GMT format, they can add `gmt` to the start of the command and the system will convert the given time (GMT) to local time after finalizing the input.

# Checklist

- [x] Add `gmt` modifier support in the date picker processor.

**Comment by limbo-yan** [comment]
Updated in indigo-103-cy-date-picker branch.
