### ISSUE TITLE
[Navigation] Navigation breaks when clicking Business Process from log detail page.

### ISSUE THREAD

**Issue by lilingxi01** [david-fisher/320-S22-Track2#217]
https://user-images.githubusercontent.com/36816148/167765327-80ae8439-ace2-4a0e-9fe4-212e44e90116.mp4

I believe you are using the relative path for navigation. You should change the link path from `./business-process` to `/business-process`.

**Comment by Animesh-Saxena** [comment]
Fixed. Thank you for point out.
