### ISSUE TITLE
Clicking on Donut Charts/Business Processes Data Loading Error

### ISSUE THREAD

**Issue by mcrummetumass** [david-fisher/320-S22-Track2#228]
Clicking on a business process in the donut charts loads the Business Processes page but doesn't populate the tree or table with any data.

**Comment by mcrummetumass** [comment]
Indigo did not finish filter handling.

**Comment by lilingxi01** [comment]
We are doing it now.

**Comment by lilingxi01** [comment]
So we will populate the tree filter with given information (and automatically fetch). Not the grid. We cannot populate the grid without having an EAI transaction ID.

**Comment by lilingxi01** [comment]
Done.

The publishing business domain field is not parsed because the given one (which seems like the **Business Domain**, not **Publishing Business Domain**) does not exist in the database.

https://user-images.githubusercontent.com/36816148/167924936-b9073f44-c57d-4e1d-a623-95f27a359f68.mp4

**Comment by lilingxi01** [comment]
And also, in the given time frame, there is no any available business process (I have checked that with manual API). I have no idea why there are some in the chart.
