### ISSUE TITLE
[BPTreeView] Reorganize treeview files.

### ISSUE THREAD

**Issue by nekomi2** [david-fisher/320-S22-Track2#52]
- [x] Right now I'm just putting everything in the treeview.js, we should see if we can pull stuff out into different files.
- [x] Also looking delete treemap.js, but I need to ask @lilingxi01 if it does anything special with the parameters
- [x] Find what we can reuse for the different treeitem files, then delete them all later since they're mostly duplicate code
  - We should be able to delete them all and replace with new tree item render functions.
- [x] Setup the prototype style of `<TreeItem>`.
- [x] Setup the prototype style of `<TreeContextMenu>`.
- [x] Organize the reusable part of render functions.
  - It is not necessary to put render functions into different file if we are not going to change a lot in the tree view.
  - But it is okay to do so if we want to avoid potential conflict and after organizing the reusable parts.

We are going to merge after the final todo is finished.

**Comment by lilingxi01** [comment]
> Also looking delete treemap.js, but I need to ask @lilingxi01 if it does anything special with the parameters

We can now remove the old `BPTreeMap` component (located at `/components/business-process/tree/tree-map.js`) and its file (`tree-map.js`). It was served for the customized vanilla tree map component.

The parameter `onChange` will be added later in order to pass information to BPActivityView. But we don't need it yet.

**Comment by lilingxi01** [comment]
@nekomi2 @limbo-yan I have created a new branch `indigo-52-organize-treeview` so we can work on the same branch for everything related to this issue (#52).

**Comment by lilingxi01** [comment]
> Find what we can reuse for the different treeitem files, then delete them all later since they're mostly duplicate code

The reason why I was putting different hierarchy tree item into different files is that there will be some differences between different hierarchy of tree items. For example, EAI domain hierarchy will probably have a more stand-out item design and different hierarchy have different right click menu texts and functionalities.

What we should do for this issue could be separating out the things that can be reused and things that may be differed. For reusable part, we can put them in the `tree-view.js` file, and then put hierarchy-specific things (`<TreeItem>` for four different hierarchy) into separate files, where they will import the reusable part from `tree-view.js`.

**Comment by lilingxi01** [comment]
> Right now I'm just putting everything in the treeview.js, we should see if we can pull stuff out into different files.

I quickly refined the style of tree items and we need to optimize the reusability (for both styles and tree items) later this week! If you are free, you can do so and commit it!
