### ISSUE TITLE
[BPTreeView] Add shortcut command features to DatePicker.

### ISSUE THREAD

**Issue by lilingxi01** [david-fisher/320-S22-Track2#60]
# Functionality Checklist
- [x] Support rough date format.
  - Sample format: `12/20/2022 9am`, `12/20/2022 9:00`, and `12/20/2022 9 AM` should all be able to parse automatically into `12/20/2022 9:00 AM` (the correct DateTime object).
- [x] Support date modifier `h` (hour), `m` (minute), `d` (day), `mo` (month), `y` (year).
  - It includes three parts: modifier prefix (`-` or `+`), the modifying amount (a number), and the modifying unit (the shortcut for time units).
- [x] Support multiple modifier at the same time.
  - Multiple modifier terms will be separated by spaces.
  - Sample format: `-1mo +1d 9am` equals to 1 month earlier, 1 day later (based on the modifier before), and at 9 AM.
- [x] The start date field will parse the command based on current time.
- [x] The end date field will parse the command based on the start date.
- [x] Add help documentation for the shortcut commands.
- [x] Support date format parsing and separated time format parsing (read from user input `9:00 AM`).
- [x] Support the date format that only has month and day.
  - For example, `03/28` will be parsed into `3/28/2022` (do not modify the year).
# Issues
- [x] When there is no start date, the end date should be parsed based on now rather than 50 years ago lmao.
- [x] The parsing is happened when input is still in progress. It should only parse when the input is finished.
- [x] The close button inside the modal is not at the really right position.
- [x] The base date of the start date is initialized when entering the page, not when doing the request.

**Comment by lilingxi01** [comment]
@limbo-yan Our work for shortcut commands should go into the branch `indigo-60-shortcut`.

**Comment by limbo-yan** [comment]
Issue[3/28/2022 12:49 AM]: Only when I use the material UI date picker for the start date, the base date will work for the end date. If I input the start date by typing, the end date field won't parse the command successfully.

**Comment by lilingxi01** [comment]
@limbo-yan Right now it is finishing the parsing once I type a space. It seems like you are parsing the command while the input is changing. `useEffect` will be called everytime the given dependency value is changed.

It would be better if you update the date value only when Enter is pressed. So after pressing the enter or clicking anywhere else, the user can then see the final parsed date, and before pressing the enter, we do not modify the old picked date (so if user want to discard the changes, they can simply click anywhere else to cancel it except it is a date format or the input field is blank).

**Comment by limbo-yan** [comment]
> 

Okay sure. I will implement the enter thing when I start the multiple modifiers implementation.

**Comment by limbo-yan** [comment]
@lilingxi01 Okay sure. I will implement the enter thing when I start the multiple modifiers implementation.

**Comment by limbo-yan** [comment]
Issue[3/28/2022 2:02 AM]: Created the initial tooltip. Need to think about how to explain the help documentation concise and straightforward.

**Comment by lilingxi01** [comment]
Added a standalone helper modal component (WIP). Fixed some syntax issues and some mini bugs.
